name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1: Check out repository.
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2: Set up Docker.
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 3: Build the Docker image.
      - name: Build Docker image
        run: |
          docker build -t harrysdiner-backend:latest ./backend

      # 4: Export Docker image to a tar file.
      - name: Save Docker image as tar
        run: |
          docker save harrysdiner-backend:latest > harrysdiner-backend.tar

      # 5: Copy Docker image to EC2.
      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: harrysdiner-backend.tar
          target: /home/${{ secrets.EC2_USER }}

      # 6: Load Docker image and start container on EC2.
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker load < /home/${{ secrets.EC2_USER }}/harrysdiner-backend.tar
            docker stop harrysdiner-backend || true
            docker rm harrysdiner-backend || true
            docker run -d -p ${{ secrets.APP_PORT }}:3002 --name harrysdiner-backend harrysdiner-backend:latest
